services:
  christmas:
    image: ghcr.io/trentnbauer/radarr-schedularr:latest
    restart: unless-stopped
    environment:
      - RADARR_URL=${RADARRURL:-http://localhost:7878}
      - RADARR_API_KEY=${APIKEY}
      - LIST_NAME=Christmas
      - TZ=${TZ:-Australia/Melbourne}  
      - START_DATE=24/11 #24th of November - 1 week before Christmas (most likely will download a large amount of data - this is to ensure there is Christmas related content available ON Dec 1st)
      - END_DATE=01/01 #1st of January
      
  halloween:
    image: ghcr.io/trentnbauer/radarr-schedularr:latest
    restart: unless-stopped
    environment:
      - RADARR_URL=${RADARRURL:-http://localhost:7878}
      - RADARR_API_KEY=${APIKEY}
      - LIST_NAME=Halloween
      - TZ=${TZ:-Australia/Melbourne}  
      - START_DATE=24/09 # 24th of September - 1 week before October (most likely will download a large amount of data - this is to ensure there is Christmas related content available ON Dec 1st)
      - END_DATE=07/11 # 1 week after Halloween to compensate for late Halloween parties
      
