services:
  christmas:
    image: ghcr.io/trentnbauer/radarr-schedularr:latest
    restart: unless-stopped
    environment:
      - RADARR_URL=${RADARRURL:-http://localhost:7878}
      - RADARR_API_KEY=${APIKEY}
      - LIST_NAME=Christmas
      - TZ=${TZ:-Australia/Melbourne}  
      - START_DATE=29/11 #29th of November
      - END_DATE=01/01 #1st of January
      
  halloween:
    image: ghcr.io/trentnbauer/radarr-schedularr:latest
    restart: unless-stopped
    environment:
      - RADARR_URL=${RADARRURL:-http://localhost:7878}
      - RADARR_API_KEY=${APIKEY}
      - LIST_NAME=Halloween
      - TZ=${TZ:-Australia/Melbourne}  
      - START_DATE=01/09
      - END_DATE=02/11
      
